// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
)

const listSongs = `-- name: ListSongs :many
SELECT id, title, artist, release_date, lyrics, link FROM song
ORDER BY id
`

func (q *Queries) ListSongs(ctx context.Context) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.ReleaseDate,
			&i.Lyrics,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
